all: p1, p2, p3, p4
	
p1:
  g++ -Wl,--no-as-needed -lGLU -lGL -lglut primjer1.cpp -o p1.out
p2:
  g++ -Wl,--no-as-needed -lGLU -lGL -lglut primjer2.cpp -o p2.out
p3:
  g++ -Wl,--no-as-needed -lGLU -lGL -lglut primjer3.cpp -o p3.out
p4:
  g++ -Wl,--no-as-needed -lGLU -lGL -lglut primjer4.cpp -o p4.out

clean:
	rm *.exe *.out